command: ["uvicorn", "yao_demo_vehicle_app.backend.app:app", "--workers", "2"]
user_api_scopes:
  - "iam.current-user:read"
  - "iam.access-control:read"
env:
  - name: DATABRICKS_HOST
    value: "https://<your-workspace>.cloud.databricks.com"
  - name: YAO_DEMO_VEHICLE_APP_UNITY__CATALOG
    value: <your_catalog>
  - name: YAO_DEMO_VEHICLE_APP_UNITY__SCHEMA_NAME
    value: yao_demo_vehicle_app
  - name: YAO_DEMO_VEHICLE_APP_UNITY__WAREHOUSE_ID
    value: "<your_warehouse_id>"
  - name: VOLUME_PATH
    value: "/Volumes/<your_catalog>/yao_demo_vehicle_app/videos"
